### ISSUE TITLE
Question about compute_prevalence

### ISSUE THREAD

**Issue by zkamvar** [dirkschumacher/anthro#14]
Okay,

So, I'm going through the `anthro_prevalence` function once again to try and figure out what the h\*ck is going on and I stumble across 

https://github.com/dirkschumacher/anthro/blob/97dcb8b435a4961d44c4fdc2cc89dc810bf2fea5/R/prevalence.R#L478-L479

and I'm just thinking, what madness *is* this? I'm already super tired because I've already clawed my way up to this point from the `compute_prevalence_zscore_summary()` function and now I realize I have to travel up yet another two calls to figure out where cutoff_dir and cutoffs came from.

After some (soul) searching, I realize that this function evaluates to `zscore_prev > y` or `zscore_prev < y`. Am I correct?

**Comment by dirkschumacher** [comment]
Yes. It does a simple comparison in the end.
