### ISSUE TITLE
Not able to save the results in a data frame

### ISSUE THREAD

**Issue by pranjaldhaka3005** [dirkschumacher/anthro#33]
I'm trying to analyse stunting in a sample survey data using the anthro_zscore function and wish to store the results in the data frame for further analysis. How do I save the returning results in a dataframe. Please help! 

df30 <- first_born
> with(
+     df30,
+     anthro_zscores(
+         sex = b4_01_ed,age = hw1_1,
+         weight = hw2_1_ed, measure = hw15_1_ed , lenhei = hw3_1_ed
+     )
+ )

**Comment by dirkschumacher** [comment]
You can use `cbind` to bind together data.frames by columns. See #32 for more info. 

In your case something like that should work:

```r
cbind(
  df30,
  with(
    df30,
    anthro_zscores(
      sex = b4_01_ed, age = hw1_1,
      weight = hw2_1_ed, measure = hw15_1_ed, lenhei = hw3_1_ed
    )
  )
)
```
