### ISSUE TITLE
Obtaining Z-scores for children at 60 months of age

### ISSUE THREAD

**Issue by bzki** [dirkschumacher/anthro#37]
Thanks for the excellent work on this package. 

I noticed in some exploratory code that if you input an observation with 60 months of age (given in months rather than days), then the function returns an NA for the Z-score, but not for the equivalent number days. 
See for example:
``` r
library(anthro)
anthro_zscores(sex = 1, age = 60, is_age_in_month = TRUE, armc = 16)$zac
#> [1] NA
anthro_zscores(sex = 1, age = anthro:::round_up(60*30.4375), 
               is_age_in_month = FALSE, armc = 16)$zac
#> [1] -0.37
```

<sup>Created on 2021-02-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The code doing this is here:

https://github.com/dirkschumacher/anthro/blob/855299eb35c48a57d56f191457d002a590ba5c5d/R/z-score-helper.R#L149

This occurs even though the [WHO's own tables](https://www.who.int/tools/child-growth-standards/standards/arm-circumference-for-age) have values for 60 months, and when converted into days, the age (1826 days) is in the accepted range for the other functions, e.g. https://github.com/dirkschumacher/anthro/blob/855299eb35c48a57d56f191457d002a590ba5c5d/R/z-score-arm-circumference-for-age.R#L24

If this were to be changed, it would be as simple as changing from `<` to `<=`. What are your thoughts on this? I just wanted to raise the issue in case it hadn't been discussed before, or if the above behavior was unintended.

Thanks,
BK

**Comment by dirkschumacher** [comment]
@bzki this might be interesting to you: https://github.com/WorldHealthOrganization/anthroplus
